### ISSUE TITLE
Error when trying to load /redocs/

### ISSUE THREAD

**Issue by live-wire** [whitedogg13/django-rest-framework-redocs#1]
Please find below my stack trace.
```
File "/Users/dhruv/Documents/community/unchained/venv3/lib/python3.6/site-packages/redocs/views.py", line 27, in get_endpoints
    api_parser.parse()
  File "/Users/dhruv/Documents/community/unchained/venv3/lib/python3.6/site-packages/redocs/api_parser.py", line 28, in parse
    self._parse(self.patterns, self.endpoints)
  File "/Users/dhruv/Documents/community/unchained/venv3/lib/python3.6/site-packages/redocs/api_parser.py", line 45, in _parse
    api_endpoint = ApiEndpoint(pattern, prefix)
  File "/Users/dhruv/Documents/community/unchained/venv3/lib/python3.6/site-packages/redocs/api_endpoint.py", line 11, in __init__
    self.complete_path = self._get_complete_path(pattern, prefix)
  File "/Users/dhruv/Documents/community/unchained/venv3/lib/python3.6/site-packages/redocs/api_endpoint.py", line 53, in _get_complete_path
    regex = pattern._regex if hasattr(pattern, "_regex") else pattern.pattern._regex
AttributeError: 'RoutePattern' object has no attribute '_regex'
```

**Comment by live-wire** [comment]
Hey @whitedogg13 here are my versions.
djangorestframework==3.8.2
Django==2.0.7

**Comment by whitedogg13** [comment]
Hi @live-wire , just fixed the issue and release 0.0.3. 

Please check it out and feedback if there's still any problems, thanks!

**Comment by live-wire** [comment]
I got the following error now:
```
Internal Server Error: /redocs/
Traceback (most recent call last):
  File "/Users/dhruv/Documents/community/unchained/venv3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/dhruv/Documents/community/unchained/venv3/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/dhruv/Documents/community/unchained/venv3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/dhruv/Documents/community/unchained/venv3/lib/python3.6/site-packages/redocs/views.py", line 31, in get_endpoints
    'endpoints': json.dumps(endpoints),
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type '__proxy__' is not JSON serializable
```

**Comment by whitedogg13** [comment]
Sorry for the late response!

This issue relates to Django translation, looks like my library doesn't handle them properly. For example, using `gettext_lazy` with `help_text` might cause this issue.

I just published a new version (0.0.4) targeting this, hope it can fix the issue for you. However since there can be other places containing translatable string, please bear with me if it remains.

Thanks a lot for reporting this!

**Comment by jayvdb** [comment]
I am using master, and see
```py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.8/site-packages/redocs/views.py", line 48, in get_endpoints
    'endpoints': json.dumps(endpoints),
  File "/usr/lib64/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type __proxy__ is not JSON serializable
```

**Comment by gurolcay** [comment]
@jayvdb can you solve `TypeError` problem about `__proxy__` ?
