### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '__name__'

### ISSUE THREAD

**Issue by jayvdb** [whitedogg13/django-rest-framework-redocs#17]
I'll bet this is due to django-attachments ...

```py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.8/site-packages/redocs/views.py", line 29, in get_endpoints
    api_parser.parse()
  File "/usr/lib/python3.8/site-packages/redocs/api_parser.py", line 28, in parse
    self._parse(
  File "/usr/lib/python3.8/site-packages/redocs/api_parser.py", line 41, in _parse
    self._parse(
  File "/usr/lib/python3.8/site-packages/redocs/api_parser.py", line 48, in _parse
    api_endpoint = ApiEndpoint(pattern, prefix)
  File "/usr/lib/python3.8/site-packages/redocs/api_endpoint.py", line 26, in __init__
    self.input_fields = self._get_serializer_fields(self.view.cls.serializer_class())
  File "/usr/lib/python3.8/site-packages/redocs/api_endpoint.py", line 104, in _get_serializer_fields
    getattr(serializer.Meta.model, key).field.related_model.__name__)
AttributeError: 'NoneType' object has no attribute '__name__'
```

**Comment by jayvdb** [comment]
Not sure about attachments, but after removing it and `drf-schemas` I then run into the `__proxy__` problem mentioned at https://github.com/whitedogg13/django-rest-framework-redocs/issues/1#issuecomment-418947491
